### ISSUE TITLE
ask for the GeoOLID dataset

### ISSUE THREAD

**Issue by lizhou21** [AnthonyMRios/Geographic-Performance-Disparities#1]
hi, I am interested in your paper[1],
the paper give the github link, but it's still empty.
Can you provide the GeoOLID dataset?
Look forward to your reply, thanks.

[1] Measuring Geographic Performance Disparities of Offensive Language Classifiers

**Comment by AnthonyMRios** [comment]
Sure, I will upload it today.

Best,
Anthony

**Comment by lizhou21** [comment]
Really thanks for that.

Best wishes,
Li

**Comment by AnthonyMRios** [comment]
The dataset has been added. Please feel free to email me if you have any other questions at anthony.rios "at" utsa.edu
